# Page title
title: "Dummy's Portfolio"
 # Header text is equivalent to title variable if not set
header: "Dummy's works"
logo_image: "sample.png"

# Service name is based on this list (without the shape prefix): http://drinchev.github.io/monosocialiconsfont/ so
#    github: "https://github.com/Dvergar/"
#    twitter: "https://twitter.com/caribouloche"
# would also be valid, different icons will be displayed.
social:
    githubalt: "https://github.com/Dvergar/"
    twitterbird: "https://twitter.com/caribouloche"
