# Page title
title: "Dummy's Portfolio"
 # Header text is equivalent to title variable if not set
header: "Dummy's works"
logo_image: "sample.png"

# Service name is based on this list (without the 'fa-' prefix): hhttp://fontawesome.io/icons/#brand
social:
    github: "https://github.com/Dvergar/"
    twitter: "https://twitter.com/caribouloche"
